5차 과제
SoongSilComputingClub/FY22-java-lotto pull request #1
Opened 2022-08-03 00:49 UTC by chjih

2022-08-04 14:38 UTC, findstar requested changes

2022-08-04 14:38 UTC, findstar commented on src/main/java/org/sscc/study/lotto/InputView.java
> +        inputValues = new InputValues(sc.nextInt());
이런경우는 비지니스 플로우가 두개로 나눠지기 때문에 
InputValues 하나로 묶지 말고 개별적인 클래스로 취급하는게 더 나아보입니다.

2022-08-04 14:38 UTC, findstar commented on src/main/java/org/sscc/study/lotto/Prize.java
> +    FIRST(6, 2000000000);
java 에서는 큰 숫자의 경우에는 
`200_000_000` 와 같이 표시할 수 있습니다. 그러면 좀 더 읽기 수월해집니다 :)

2022-08-04 14:38 UTC, findstar commented on src/main/java/org/sscc/study/lotto/Controller.java
> +        lottery.drawNumbers(new RandomLottoNumber());
RandomLottoNumber 전략이 Controller main 메소드까지 나와 있을 필요는 없어보입니다.

2022-08-04 14:38 UTC, findstar commented on src/main/java/org/sscc/study/lotto/RandomLottoNumber.java
> +    private final List<Integer> lotteryNumbers;
로또 번호자체도 별도의 클래스로 취급해서 비지니스 제약사항을 객체안에서 구현할 수 있습니다.
LottoNumber 객체를 만들어보세요.

2022-08-04 14:38 UTC, findstar commented on src/main/java/org/sscc/study/lotto/LotteryTicket.java
> +    }
LottoTicket 이 단순히 번호만 가지고 있게 하지 말고 도메인 로직을 좀 더 풍부하게 가지고 있을 수 있습니다.

2022-08-04 14:38 UTC, findstar commented on src/main/java/org/sscc/study/lotto/Prize.java
> +        return result == null ? 0 : result.prize;
null 을 활용하기 보다는 Prize.NONE 을 만드는건 어떤가요?

2022-08-05 07:59 UTC, chjih commented on src/main/java/org/sscc/study/lotto/Controller.java
> +        lottery.drawNumbers(new RandomLottoNumber());
이전 과제와 비슷하게 테스트를 위해서 random에 관한 내용을 외부에서 주입 받을 수 있게 했는데 RandomLottoNumber 전략이 클래스 내부로 들어가면 테스트를 어떻게 해야 할 지 모르겠습니다.

2022-08-06 14:04 UTC, findstar approved these changes
수고하셨습니다. 다음 과제 진행해주세요 👍

2022-08-06 14:04 UTC, findstar commented on src/main/java/org/sscc/study/lotto/domain/LottoNumber.java
> +public class LottoNumber implements Comparable<LottoNumber> {
`comparable` 👍

2022-08-06 14:04 UTC, merged